### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lilcsz** [brentvollebregt/auto-py-to-exe#110]
C:\Users\Lil\Downloads\auto-py-to-exe-master>python run.py
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\gevent\threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 0: invalid start byte
2020-07-29T09:47:53Z (<ThreadPoolWorker at 0x440eac8 thread_ident=0x3810 threadpool-hub=<Hub at 0x43ab918 thread_ident=0x335c>>, <built-in function gethostbyaddr>) failed with UnicodeDecodeError

Traceback (most recent call last):
  File "run.py", line 9, in <module>
    apte.run()
  File "C:\Users\Lil\Downloads\auto-py-to-exe-master\auto_py_to_exe\__main__.py", line 99, in run
    start_ui(logging_level)
  File "C:\Users\Lil\Downloads\auto-py-to-exe-master\auto_py_to_exe\__main__.py", line 22, in start_ui
    ui.start(config.ui_open_mode)
  File "C:\Users\Lil\Downloads\auto-py-to-exe-master\auto_py_to_exe\ui.py", line 140, in start
    eel.start('index.html', size=(650, 650), port=0)
  File "D:\Python\lib\site-packages\eel\__init__.py", line 164, in start
    run_lambda()
  File "D:\Python\lib\site-packages\eel\__init__.py", line 155, in run_lambda
    return btl.run(
  File "D:\Python\lib\site-packages\bottle.py", line 3137, in run
    server.run(app)
  File "D:\Python\lib\site-packages\bottle_websocket\server.py", line 17, in run
    server.serve_forever()
  File "D:\Python\lib\site-packages\gevent\baseserver.py", line 398, in serve_forever
    self.start()
  File "D:\Python\lib\site-packages\gevent\baseserver.py", line 336, in start
    self.init_socket()
  File "D:\Python\lib\site-packages\gevent\pywsgi.py", line 1501, in init_socket
    self.update_environ()
  File "D:\Python\lib\site-packages\gevent\pywsgi.py", line 1513, in update_environ
    name = socket.getfqdn(address[0])
  File "D:\Python\lib\site-packages\gevent\_socketcommon.py", line 287, in getfqdn
    hostname, aliases, _ = gethostbyaddr(name)
  File "D:\Python\lib\site-packages\gevent\_socketcommon.py", line 259, in gethostbyaddr
    return get_hub().resolver.gethostbyaddr(ip_address)
  File "D:\Python\lib\site-packages\gevent\resolver\thread.py", line 66, in gethostbyaddr
    return self.pool.apply(_socket.gethostbyaddr, args, kwargs)
  File "D:\Python\lib\site-packages\gevent\pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src\\gevent\\event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "D:\Python\lib\site-packages\gevent\_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "D:\Python\lib\site-packages\gevent\threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 0: invalid start byte

**Comment by brentvollebregt** [comment]
Was there any output in the tool itself that you could provide?

**Comment by lilcsz** [comment]
I installed python 3.7 working now but i have this error: no module named pkg

**Comment by brentvollebregt** [comment]
> no module named pkg

Is that all? Was there any more output with this error?

**Comment by lilcsz** [comment]
yes only no module named pkg

**Comment by brentvollebregt** [comment]
@lilcsz could you please provide a screenshot of the error in auto-py-to-exe's UI?

**Comment by brentvollebregt** [comment]
Closing due to no further information provided from @lilcsz for over three months.
