### ISSUE TITLE
```ModuleNotFoundError: No module named 'pkg_resources.py2_warn'```

### ISSUE THREAD

**Issue by OfekShochat** [brentvollebregt/auto-py-to-exe#114]
its an issue I'm facing for a while now with 3.8... is this the lack of 3.8 support of pyinstaller? it is the same when I did it like a year ago. (when I tried to do this with a lot of libs. like cx_freeze, pyinstaller directly and more )
this is the traceback:

Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 13, in <module>
  File "C:\Users\o\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[25956] Failed to execute script pyi_rth_pkgres

**Comment by brentvollebregt** [comment]
It looks like pypa/setuptools#1963 could give some insight into what is happening here. 

Try using setuptools 45.0.0 using `pip install --upgrade 'setuptools<45.0.0'` - does this fix your issue?

**Comment by brentvollebregt** [comment]
There has been no response by @OfekShochat in more than three months so I'm going to assume this was resolved.
