### ISSUE TITLE
Fatal error - after a recompile 

### ISSUE THREAD

**Issue by farinavito** [brentvollebregt/auto-py-to-exe#123]
**Using:**

- Pycharm Community Edition 2019.2.2

- Python 3.7.4

- Windows 10

I am creating a gui (tkinter) app. I was initially able to compile .py to .exe using auto-py-to-exe, however, I was unable to recompiled it after having made some changes.

**Changes:**

- added dask (library)

- imported itertools

After trying to create a new .exe file, I get a Fatal error. Below you can see the output from auto-py-to-exe:

```
Running auto-py-to-exe v2.7.8
Building directory: C:\Users\UPORAB~1\AppData\Local\Temp\tmpsb8d3z3q
Provided command: pyinstaller --noconfirm --onedir --windowed --debug "all"  "C:/Users/Uporabnik/PycharmProjects/skb_gui/gui.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onedir --windowed --debug all C:/Users/Uporabnik/PycharmProjects/skb_gui/gui.py --distpath C:\Users\UPORAB~1\AppData\Local\Temp\tmpsb8d3z3q\application --workpath C:\Users\UPORAB~1\AppData\Local\Temp\tmpsb8d3z3q\build --specpath C:\Users\UPORAB~1\AppData\Local\Temp\tmpsb8d3z3q

1564601 INFO: PyInstaller: 4.0
1564604 INFO: Python: 3.7.4
1564608 INFO: Platform: Windows-10-10.0.18362-SP0
1564614 INFO: wrote C:\Users\UPORAB~1\AppData\Local\Temp\tmpsb8d3z3q\gui.spec
1564673 INFO: UPX is not available.
1564705 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Uporabnik\\PycharmProjects\\skb_gui',
 'C:\\Users\\UPORAB~1\\AppData\\Local\\Temp\\tmpsb8d3z3q']
1564826 INFO: checking Analysis
1564832 INFO: Building Analysis because Analysis-01.toc is non existent
1564871 INFO: Reusing cached module dependency graph...
1565004 INFO: Caching module graph hooks...
1566432 INFO: running Analysis Analysis-01.toc
1566489 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\uporabnik\appdata\local\programs\python\python37-32\python.exe
1566719 INFO: Analyzing C:\Users\Uporabnik\PycharmProjects\skb_gui\gui.py
1572991 INFO: Processing pre-find module path hook distutils from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
1573047 INFO: distutils: retargeting to non-venv dir 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib'
1586877 INFO: Processing pre-find module path hook site from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
1586891 INFO: site: retargeting to fake-dir 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\fake-modules'
1603127 INFO: Processing pre-safe import module hook six.moves from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
1669789 INFO: Processing module hooks...
1669795 INFO: Loading module hook 'hook-dask.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1670913 INFO: Loading module hook 'hook-eel.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1671271 INFO: Loading module hook 'hook-IPython.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1671996 INFO: Excluding import 'PyQt5'
1672010 INFO:   Removing import of PyQt5 from module IPython.external.qt_loaders
1672015 INFO: Excluding import 'gtk'
1672034 INFO: Excluding import 'PySide'
1672049 INFO:   Removing import of PySide from module IPython.external.qt_loaders
1672054 INFO: Excluding import 'tkinter'
1672071 INFO:   Removing import of tkinter from module IPython.lib.clipboard
1672083 INFO: Excluding import 'PyQt4'
1672102 INFO:   Removing import of PyQt4 from module IPython.external.qt_loaders
1672107 INFO: Excluding import 'matplotlib'
1672131 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
1672139 INFO: Loading module hook 'hook-jedi.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1673966 INFO: Loading module hook 'hook-jinja2.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1674017 INFO: Loading module hook 'hook-jsonschema.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1674097 INFO: Loading module hook 'hook-nbconvert.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1674443 INFO: Loading module hook 'hook-nbformat.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1674632 INFO: Loading module hook 'hook-notebook.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1685369 INFO: Loading module hook 'hook-openpyxl.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1685849 INFO: Loading module hook 'hook-pycparser.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1685859 INFO: Loading module hook 'hook-zmq.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1688469 INFO: Loading module hook 'hook-distutils.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1688499 INFO: Loading module hook 'hook-encodings.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1688628 INFO: Loading module hook 'hook-gevent.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1690469 WARNING: Unable to find package for requirement greenlet from package gevent.
1690477 WARNING: Unable to find package for requirement zope.event from package gevent.
1690489 WARNING: Unable to find package for requirement zope.interface from package gevent.
1690502 INFO: Packages required by gevent:
['setuptools', 'cffi']
1693800 INFO: Loading module hook 'hook-importlib_metadata.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1693845 INFO: Loading module hook 'hook-lib2to3.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1693988 INFO: Loading module hook 'hook-numpy.core.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1694013 INFO: Loading module hook 'hook-numpy.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1694030 INFO: Loading module hook 'hook-pandas.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1699310 INFO: Loading module hook 'hook-pkg_resources.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1700256 INFO: Processing pre-safe import module hook win32com from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
1700704 WARNING: Hidden import "pkg_resources.py2_warn" not found!
1700713 WARNING: Hidden import "pkg_resources.markers" not found!
1700731 INFO: Excluding import '__main__'
1700749 INFO:   Removing import of __main__ from module pkg_resources
1700762 INFO: Loading module hook 'hook-pygments.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1705760 INFO: Loading module hook 'hook-pytz.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1706267 INFO: Loading module hook 'hook-setuptools.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1707578 INFO: Loading module hook 'hook-sqlite3.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1707847 INFO: Loading module hook 'hook-sysconfig.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1707869 INFO: Loading module hook 'hook-wcwidth.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1707978 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1707989 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1708007 INFO: Loading module hook 'hook-xml.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1708024 INFO: Loading module hook 'hook-_tkinter.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
1708525 INFO: checking Tree
1708535 INFO: Building Tree because Tree-02.toc is non existent
1708551 INFO: Building Tree Tree-02.toc
1709157 INFO: checking Tree
1709167 INFO: Building Tree because Tree-03.toc is non existent
1709187 INFO: Building Tree Tree-03.toc
1709268 INFO: Loading module hook 'hook-pythoncom.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1710208 INFO: Loading module hook 'hook-pywintypes.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1710837 INFO: Loading module hook 'hook-win32com.py' from 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
1712219 INFO: Looking for ctypes DLLs
1712458 INFO: Analyzing run-time hooks ...
1712494 INFO: Including run-time hook 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_traitlets.py'
1712529 INFO: Including run-time hook 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
1712561 INFO: Including run-time hook 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32comgenpy.py'
1712593 INFO: Including run-time hook 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
1712612 INFO: Including run-time hook 'c:\\users\\uporabnik\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
1712697 INFO: Looking for dynamic libraries
1717889 INFO: Looking for eggs
1717900 INFO: Using Python library c:\users\uporabnik\appdata\local\programs\python\python37-32\python37.dll
1717921 INFO: Found binding redirects: 
[]
1736120 INFO: Warnings written to C:\Users\UPORAB~1\AppData\Local\Temp\tmpsb8d3z3q\build\gui\warn-gui.txt
1736917 INFO: Graph cross-reference written to C:\Users\UPORAB~1\AppData\Local\Temp\tmpsb8d3z3q\build\gui\xref-gui.html
1737448 INFO: checking PYZ
1737459 INFO: Building PYZ because PYZ-01.toc is non existent
1737476 INFO: Building PYZ (ZlibArchive) C:\Users\UPORAB~1\AppData\Local\Temp\tmpsb8d3z3q\build\gui\PYZ-01.pyz
1737495 INFO: Building PYZ (ZlibArchive) C:\Users\UPORAB~1\AppData\Local\Temp\tmpsb8d3z3q\build\gui\PYZ-01.pyz completed successfully.
1737528 INFO: checking PKG
1737542 INFO: Building PKG because PKG-01.toc is non existent
1737566 INFO: Building PKG (CArchive) PKG-01.pkg
1737745 INFO: Building PKG (CArchive) PKG-01.pkg completed successfully.
1737758 INFO: Bootloader c:\users\uporabnik\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\runw_d.exe
1737775 INFO: checking EXE
1737792 INFO: Building EXE because EXE-01.toc is non existent
1737811 INFO: Building EXE from EXE-01.toc
1737967 INFO: Appending archive to EXE C:\Users\UPORAB~1\AppData\Local\Temp\tmpsb8d3z3q\build\gui\gui.exe
1739676 INFO: Building EXE from EXE-01.toc completed successfully.
1739726 INFO: checking COLLECT
1739737 INFO: Building COLLECT because COLLECT-01.toc is non existent
1739758 INFO: Building COLLECT COLLECT-01.toc
1876812 INFO: Building COLLECT COLLECT-01.toc completed successfully.

Moving project to: C:\Users\Uporabnik\PycharmProjects\skb_gui\output
Complete.
```
Based on this [issue](https://github.com/pypa/setuptools/issues/1963) I have updated  setuptools to latest version ->50.3.0. I have also upgraded pip to latest version -> 20.2.3. I  have also read all open and closed issuess from auto-py-to-exe, however, nothing seems similiar to my issue. 

I've also found some articles on cffi [issues](https://github.com/samuelhwilliams/Eel/issues/75) and gevent [issues](https://github.com/pyinstaller/pyinstaller/issues/242), however, no solution has helped.

I have tried --hidden-import=pkg_resources.py2_warn --hidden-import=pkg_resources.markers and it did not helped. 

Any suggestions what to do next?

**Comment by brentvollebregt** [comment]
I don't see "Fatal error" in that output you have provided so I'm going to assume this message appears when you actually run the created executable (correct me if I'm wrong).

Did you read my post that is linked in the tool itself after each build and in the README? In that post there is a [Debugging](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#debugging) section that explains how to debug in situations like this (also [this](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#fatal-error-failed-to-execute)). Have you given this a read? Was there an error when running the executable from the terminal?

**Comment by farinavito** [comment]
Thank you for your reply. The "Fatal error" that I was receiving appeared after I had run the script. 

After reading the article you had mentioned, I received this error: 
```
Traceback (most recent call last):
  File "c:\users\uporabnik\appdata\local\programs\python\python37-32\lib\site-packages\dask\dataframe\__init__.py", line 2, in <module>
    from .core import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\uporabnik\appdata\local\programs\python\python37-32\lib\site-packages\dask\dataframe\core.py", line 18, in <module>
    from tlz import merge, first, unique, partition_all, remove
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tlz'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\uporabnik\appdata\local\programs\python\python37-32\lib\site-packages\dask\dataframe\__init__.py", line 57, in <module>
    raise ImportError(msg) from e
ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install
```
After typing `python -m pip install "dask[dataframe]" --upgrade` in my cmd, my python script was compiled to .exe and everything works as it should.

Therefore, I am closing this issue report.
