### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [brentvollebregt/auto-py-to-exe#139]
Every time I run auto-py-to-exe it errors with...

`18084 ERROR: An error occurred while packaging
Traceback (most recent call last):
  File "c:\Users\pc\Desktop\auto-py-to-exe-master\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 720, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 667, in build
    exec(code, spec_namespace)
  File "C:\Users\pc\AppData\Local\Temp\tmps8mfmpy9\app.spec", line 6, in <module>
    a = Analysis(['C:/Users/pc/Desktop/[1] All my Projects/JS Quick Pack/Program/app.py'],
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
    self.__postinit__()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 419, in assemble
    self.graph.process_post_graph_hooks()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\depend\analysis.py", line 367, in process_post_graph_hooks
    module_hook.post_graph()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\depend\imphook.py", line 447, in post_graph
    self._load_hook_module()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\depend\imphook.py", line 408, in _load_hook_module
    self._hook_module = importlib_load_source(
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\compat.py", line 593, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 469, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 969, in load_module
  File "<frozen importlib._bootstrap_external>", line 794, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\hooks\hook-numpy.core.py", line 29, in <module>
    pkg_base, pkg_dir = get_package_paths('numpy.core')
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 506, in get_package_paths
    file_attr = get_module_file_attribute(package)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 289, in get_module_file_attribute
    loader = pkgutil.find_loader(package)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\pkgutil.py", line 494, in find_loader
    spec = importlib.util.find_spec(fullname)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\importlib\util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 138, in <module>
    from . import _distributor_init
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application`

I have no idea what could be the problem. I just spent 3 hours reinstalling auto-py-to-exe, it's modules and python but it's still throwing this OS error. I'm not very experienced with python since I'm a beginner so the problem may be more obvious to you devs.

**Comment by THEGOLDENPRO** [comment]
Okay, now the error has changed to this...

`Traceback (most recent call last):
  File "c:/Users/pc/Desktop/auto-py-to-exe-master/run.py", line 6, in <module>
    from auto_py_to_exe import __main__ as apte
  File "c:\Users\pc\Desktop\auto-py-to-exe-master\auto_py_to_exe\__main__.py", line 10, in <module>
    from . import ui
  File "c:\Users\pc\Desktop\auto-py-to-exe-master\auto_py_to_exe\ui.py", line 5, in <module>
    import eel
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\eel\__init__.py", line 5, in <module>
    import gevent as gvt
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'`

**Comment by THEGOLDENPRO** [comment]
Nevermind I fixed the issue myself.
