### ISSUE TITLE
When run auto-py-to-exe with --onefile option I get OSError: [WinError 5] Access is denied, and can not get my .exe file

### ISSUE THREAD

**Issue by ScorpJ** [brentvollebregt/auto-py-to-exe#160]
Here is some log from the tool.I am not sure what happened and how can I get the right thing.Bellow is the log I got
Running auto-py-to-exe v2.8.0
Building directory: C:\Users\s1028125\AppData\Local\Temp\tmpxacebnay
Provided command: pyinstaller --noconfirm --onefile --windowed --log-level "CRITICAL" --debug "all"  "C:/projects/python/BackCross2SpreadSheetGUI.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --windowed --log-level CRITICAL --debug all C:/projects/python/BackCross2SpreadSheetGUI.py --distpath C:\Users\s1028125\AppData\Local\Temp\tmpxacebnay\application --workpath C:\Users\s1028125\AppData\Local\Temp\tmpxacebnay\build --specpath C:\Users\s1028125\AppData\Local\Temp\tmpxacebnay

An error occurred while packaging
Traceback (most recent call last):
  File "c:\myapps\anaconda3\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "c:\myapps\anaconda3\lib\site-packages\win32ctypes\pywin32\win32api.py", line 229, in EndUpdateResource
    _resource._EndUpdateResource(handle, discard)
  File "c:\myapps\anaconda3\lib\site-packages\win32ctypes\core\cffi\_resource.py", line 123, in _EndUpdateResource
    check_false(
  File "c:\myapps\anaconda3\lib\site-packages\win32ctypes\core\cffi\_util.py", line 81, in __call__
    self._raise_error(function_name)
  File "c:\myapps\anaconda3\lib\site-packages\win32ctypes\core\cffi\_util.py", line 92, in _raise_error
    raise exception
OSError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\myapps\anaconda3\lib\site-packages\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "c:\myapps\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\myapps\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\myapps\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 725, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\myapps\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 672, in build
    exec(code, spec_namespace)
  File "C:\Users\s1028125\AppData\Local\Temp\tmpxacebnay\BackCross2SpreadSheetGUI.spec", line 20, in <module>
    exe = EXE(pyz,
  File "c:\myapps\anaconda3\lib\site-packages\PyInstaller\building\api.py", line 450, in __init__
    self.__postinit__()
  File "c:\myapps\anaconda3\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\myapps\anaconda3\lib\site-packages\PyInstaller\building\api.py", line 602, in assemble
    self.manifest.update_resources(tmpnm, [1])
  File "c:\myapps\anaconda3\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 949, in update_resources
    UpdateManifestResourcesFromXML(dstpath,
  File "c:\myapps\anaconda3\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1027, in UpdateManifestResourcesFromXML
    winresource.UpdateResources(dstpath, xmlstr, RT_MANIFEST, names or [name],
  File "c:\myapps\anaconda3\lib\site-packages\PyInstaller\utils\win32\winresource.py", line 205, in UpdateResources
    win32api.EndUpdateResource(hdst, 0)
  File "c:\myapps\anaconda3\lib\site-packages\win32ctypes\pywin32\win32api.py", line 229, in EndUpdateResource
    _resource._EndUpdateResource(handle, discard)
  File "c:\myapps\anaconda3\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\myapps\anaconda3\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (5, 'EndUpdateResource', 'Access is denied')

Project output will not be moved to output folder
Complete.

**Comment by ScorpJ** [comment]
When changed to--onedir get beollow error when run the exe.

**Comment by brentvollebregt** [comment]
> OSError: [WinError 5] Access is denied

Have you tried giving the script elevated permissions? It is probably trying to access a file it is not allowed to.

**Comment by ScorpJ** [comment]
Yes,even run as admin, it is still get the same erroe.

**Comment by brentvollebregt** [comment]
Could you create a new Python virtual environment, install auto-py-to-exe and your dependencies and then try to run the tool from this virtual environment please?

**Comment by ScorpJ** [comment]
it's ok on my personal labtop, but has issue  on my work labtop.

**Comment by brentvollebregt** [comment]
Unless you can identify the difference there is not much I can help with sorry

**Comment by brentvollebregt** [comment]
> since I can use pyinstaller directly

Sorry, I am not sure what you mean? How did you fix your issue?

**Comment by ScorpJ** [comment]
I did not fix the issue just find a workaround to use  pyinstaller  directlly.

**Comment by BB6560** [comment]
And what would that mysterious workaround of yours be? :)

The only workaround that solved the problem for me is moving the project's folder to another place. For example I moved it directly to D:\ and the error disappeared. I have no idea why btw, but I hope this helps someone.

**Comment by connorhess** [comment]
this is still an issue, I got it on my work and personal laptop after compiling a few times, will try the work arround

**Comment by vrawat26** [comment]
just create new virtual enviornment and run autopy there
