### ISSUE TITLE
Packaging Error - "AttributeError: 'NoneType' object has no attribute 'groups'" in load_ldconfig_cache

### ISSUE THREAD

**Issue by therealOri** [brentvollebregt/auto-py-to-exe#161]
This is the error I get when packaging towards the end of the process.
I don't know how to fix this or what the issue is. Any help is appreciated.

```
An error occurred while packaging
Traceback (most recent call last):
  File "/home/ori/auto-py-to-exe/auto_py_to_exe/packaging.py", line 131, in package
    run_pyinstaller()
  File "/home/ori/.local/lib/python3.9/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/ori/.local/lib/python3.9/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/ori/.local/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 725, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/ori/.local/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 672, in build
    exec(code, spec_namespace)
  File "/tmp/tmpo9r2bhx_/bump.spec", line 6, in <module>
    a = Analysis(['/home/ori/Desktop/Projects/bump.py'],
  File "/home/ori/.local/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 242, in __init__
    self.__postinit__()
  File "/home/ori/.local/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/home/ori/.local/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 438, in assemble
    ctypes_binaries = scan_code_for_ctypes(co)
  File "/home/ori/.local/lib/python3.9/site-packages/PyInstaller/depend/utils.py", line 145, in scan_code_for_ctypes
    binaries = _resolveCtypesImports(binaries)
  File "/home/ori/.local/lib/python3.9/site-packages/PyInstaller/depend/utils.py", line 319, in _resolveCtypesImports
    load_ldconfig_cache()
  File "/home/ori/.local/lib/python3.9/site-packages/PyInstaller/depend/utils.py", line 402, in load_ldconfig_cache
    path = m.groups()[-1]
AttributeError: 'NoneType' object has no attribute 'groups'

Project output will not be moved to output folder
Complete.
```

**Comment by brentvollebregt** [comment]
Check out pyinstaller/pyinstaller#5540 - this is a known issue with pyinstaller at the moment.
