### ISSUE TITLE
UTF-8 codec cant be decoded

### ISSUE THREAD

**Issue by CodelessHeart** [brentvollebregt/auto-py-to-exe#173]
I install according to the instructions.

`Traceback (most recent call last):
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\gevent\threadpool.py", line 167, in __run_task
    thread_result.set(func(*args, **kwargs))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 8: invalid
continuation byte
2021-05-19T14:39:38Z (<ThreadPoolWorker at 0x481b670 thread_ident=0x1028 threadp
ool-hub=<Hub at 0x4404640 thread_ident=0x91c>>, <built-in function gethostbyaddr
>) failed with UnicodeDecodeError

Traceback (most recent call last):
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\Scripts\auto-py-
to-exe-script.py", line 33, in <module>
    sys.exit(load_entry_point('auto-py-to-exe==2.9.0', 'console_scripts', 'auto-
py-to-exe')())
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\auto_py_to_exe\__main__.py", line 99, in run
    start_ui(logging_level)
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\auto_py_to_exe\__main__.py", line 22, in start_ui
    ui.start(config.ui_open_mode)
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\auto_py_to_exe\ui.py", line 140, in start
    eel.start('index.html', size=(650, 672), port=0)
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\eel\__init__.py", line 164, in start
    run_lambda()
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\eel\__init__.py", line 155, in run_lambda
    return btl.run(
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\Scripts\bottle.p
y", line 3137, in run
    server.run(app)
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\bottle_websocket\server.py", line 17, in run
    server.serve_forever()
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\gevent\baseserver.py", line 398, in serve_forever
    self.start()
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\gevent\baseserver.py", line 336, in start
    self.init_socket()
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\gevent\pywsgi.py", line 1546, in init_socket
    self.update_environ()
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\gevent\pywsgi.py", line 1558, in update_environ
    name = socket.getfqdn(address[0])
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\gevent\_socketcommon.py", line 304, in getfqdn
    hostname, aliases, _ = gethostbyaddr(name)
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\gevent\_socketcommon.py", line 276, in gethostbyaddr
    return get_hub().resolver.gethostbyaddr(ip_address)
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\gevent\resolver\thread.py", line 66, in gethostbyaddr
    return self.pool.apply(_socket.gethostbyaddr, args, kwargs)
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\gevent\pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src\\gevent\\event.py", line 329, in gevent._gevent_cevent.AsyncResult.g
et
  File "src\\gevent\\event.py", line 359, in gevent._gevent_cevent.AsyncResult.g
et
  File "src\\gevent\\event.py", line 347, in gevent._gevent_cevent.AsyncResult.g
et
  File "src\\gevent\\event.py", line 327, in gevent._gevent_cevent.AsyncResult._
raise_exception
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\gevent\_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\LLonB7UtV97nMVRn1w2bM656PLog19npoEhon\Python38\lib\site-package
s\gevent\threadpool.py", line 167, in __run_task
    thread_result.set(func(*args, **kwargs))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 8: invalid
continuation byte`

**Comment by brentvollebregt** [comment]
What version of gevent are you running?

**Comment by CodelessHeart** [comment]
> What version of gevent are you running?
21.1.2 
```
Requirement already satisfied: gevent in c:\users\User\appdata\local\programs
\python\python38\lib\site-packages (21.1.2)
Requirement already satisfied: setuptools in c:\users\User\appdata\local\prog
rams\python\python38\lib\site-packages (from gevent) (49.2.1)
Requirement already satisfied: zope.interface in c:\users\User\appdata\local\
programs\python\python38\lib\site-packages (from gevent) (5.4.0)
Requirement already satisfied: zope.event in c:\users\User\appdata\local\prog
rams\python\python38\lib\site-packages (from gevent) (4.5.0)
Requirement already satisfied: greenlet<2.0,>=0.4.17 in c:\users\User\appdata
\local\programs\python\python38\lib\site-packages (from gevent) (1.1.0)
Requirement already satisfied: cffi>=1.12.2 in c:\users\User\appdata\local\pr
ograms\python\python38\lib\site-packages (from gevent) (1.14.4)
Requirement already satisfied: pycparser in c:\users\User\appdata\local\progr
ams\python\python38\lib\site-packages (from cffi>=1.12.2->gevent) (2.20)
```

**Comment by brentvollebregt** [comment]
Could you please use a virtual environment to install `auto-py-to-exe` and then try to use the tool from this virtual environment?
