### ISSUE TITLE
No module named 'gevent._gevent_c_hub_local'

### ISSUE THREAD

**Issue by Nekoraru22** [brentvollebregt/auto-py-to-exe#177]
When I send _auto-py-to-exe_:

```None
PS D:\Users\usuario\Downloads\auto-py-to-exe> auto-py-to-exe
Traceback (most recent call last):
  File "C:\Users\Neko\AppData\Local\Programs\Python\Python38\Scripts\auto-py-to-exe-script.py", line 33, in <module>
    sys.exit(load_entry_point('auto-py-to-exe==2.9.0', 'console_scripts', 'auto-py-to-exe')())
  File "C:\Users\Neko\AppData\Local\Programs\Python\Python38\Scripts\auto-py-to-exe-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Neko\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\Neko\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Neko\AppData\Local\Programs\Python\Python38\lib\site-packages\auto_py_to_exe-2.9.0-py3.8.egg\auto_py_to_exe\__main__.py", line 10, in <module>
    from . import ui
  File "C:\Users\Neko\AppData\Local\Programs\Python\Python38\lib\site-packages\auto_py_to_exe-2.9.0-py3.8.egg\auto_py_to_exe\ui.py", line 5, in <module>
    import eel
  File "C:\Users\Neko\AppData\Local\Programs\Python\Python38\lib\site-packages\eel\__init__.py", line 5, in <module>
    import gevent as gvt
  File "C:\Users\Neko\AppData\Local\Programs\Python\Python38\lib\site-packages\gevent\__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\Neko\AppData\Local\Programs\Python\Python38\lib\site-packages\gevent\_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "C:\Users\Neko\AppData\Local\Programs\Python\Python38\lib\site-packages\gevent\_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "C:\Users\Neko\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'

**Comment by brentvollebregt** [comment]
Did you try adding the module as a hidden import as recommended in the help post?
