### ISSUE TITLE
Lots of errors and failed to execute script

### ISSUE THREAD

**Issue by h3cker10632** [brentvollebregt/auto-py-to-exe#178]
I am trying to build a exe and when i do it did build a couple times and when it did i wuold get fatal error failed to execute script but now im trying to build it again and i get these errors 

`Running auto-py-to-exe v2.9.0
Building directory: C:\Users\leaps\AppData\Local\Temp\tmpteo1p3p_
Provided command: pyinstaller --noconfirm --onefile --windowed  "D:/desktop/Desktop folders(old)/Useful codes/DiscordChromePassStealer.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --windowed D:/desktop/Desktop folders(old)/Useful codes/DiscordChromePassStealer.py --distpath C:\Users\leaps\AppData\Local\Temp\tmpteo1p3p_\application --workpath C:\Users\leaps\AppData\Local\Temp\tmpteo1p3p_\build --specpath C:\Users\leaps\AppData\Local\Temp\tmpteo1p3p_

203634 INFO: PyInstaller: 4.2
203649 INFO: Python: 3.7.9
203650 INFO: Platform: Windows-10-10.0.19041-SP0
203665 INFO: wrote C:\Users\leaps\AppData\Local\Temp\tmpteo1p3p_\DiscordChromePassStealer.spec
203669 INFO: UPX is not available.
203681 INFO: Extending PYTHONPATH with paths
['D:\\desktop\\Desktop folders(old)\\Useful codes',
 'C:\\Users\\leaps\\AppData\\Local\\Temp\\tmpteo1p3p_']
203727 INFO: checking Analysis
203743 INFO: Building Analysis because Analysis-00.toc is non existent
203758 INFO: Initializing module dependency graph...
203778 INFO: Caching module graph hooks...
203786 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
203797 INFO: Analyzing base_library.zip ...
205333 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\leaps\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
205335 INFO: distutils: retargeting to non-venv dir 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\\lib'
206448 INFO: Caching module dependency graph...
206558 INFO: running Analysis Analysis-00.toc
An error occurred while packaging
Traceback (most recent call last):
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32ctypes\core\cffi\_dll.py", line 26, in _LoadLibraryEx
    function_name='LoadLibraryEx')
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32ctypes\core\cffi\_util.py", line 81, in __call__
    self._raise_error(function_name)
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32ctypes\core\cffi\_util.py", line 92, in _raise_error
    raise exception
OSError: [WinError 1920] The file cannot be accessed by the system

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\leaps\Downloads\auto-py-to-exe-master\auto-py-to-exe-master\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\building\build_main.py", line 725, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\building\build_main.py", line 672, in build
    exec(code, spec_namespace)
  File "C:\Users\leaps\AppData\Local\Temp\tmpteo1p3p_\DiscordChromePassStealer.spec", line 17, in <module>
    noarchive=False)
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
    self.__postinit__()
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\building\build_main.py", line 393, in assemble
    redirects=self.binding_redirects)[1:])
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\depend\bindepend.py", line 224, in Dependencies
    for ftocnm, fn in getAssemblyFiles(pth, manifest, redirects):
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\depend\bindepend.py", line 403, in getAssemblyFiles
    for assembly in getAssemblies(pth):
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\depend\bindepend.py", line 354, in getAssemblies
    res = GetManifestResources(pth)
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1016, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyInstaller\utils\win32\winresource.py", line 170, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\leaps\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (1920, 'LoadLibraryEx', 'The file cannot be accessed by the system')

Project output will not be moved to output folder
Complete.`

**Comment by brentvollebregt** [comment]
Have you read the help post that is linked at the bottom of the UI after each build (and many other places)

**Comment by Dwalinnewyork** [comment]
[README.md](https://github.com/brentvollebregt/auto-py-to-exe/files/6919240/README.md)
