### ISSUE TITLE
Packaging error

### ISSUE THREAD

**Issue by NONPLAYT** [brentvollebregt/auto-py-to-exe#216]
When Im trying to pack, I get error
```An error occurred while packaging
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 782, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 714, in build
    exec(code, spec_namespace)
  File "C:\Users\Admin\AppData\Local\Temp\tmpb6cbk_xo\main.spec", line 7, in <module>
    a = Analysis(['E:/GitHub/repository/BXNuker/main.py'],
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 277, in __init__
    self.__postinit__()
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\datastruct.py", line 155, in __postinit__
    self.assemble()
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 439, in assemble
    priority_scripts.append(self.graph.add_script(script))
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\depend\analysis.py", line 265, in add_script
    self._top_script_node = super().add_script(pathname)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1433, in add_script
    self._process_imports(n)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\depend\analysis.py", line 387, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\depend\analysis.py", line 387, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2510, in _safe_import_hook
    self.import_hook(
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1544, in import_hook
    for target_submodule in self._import_importable_package_submodules(
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1794, in _import_importable_package_submodules
    submodule = self._safe_import_module(
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\depend\analysis.py", line 387, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1518, in import_hook
    submodule = self._safe_import_module(head, mname, submodule)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\depend\analysis.py", line 377, in _safe_import_module
    hook_module.pre_safe_import_module(hook_api)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\hooks\pre_safe_import_module\hook-urllib3.packages.six.moves.py", line 32, in pre_safe_import_module
    raise SystemExit("pre-safe-import-module hook failed, needs fixing.")
SystemExit: pre-safe-import-module hook failed, needs fixing.

Project output will not be moved to output folder
Complete.```

**Comment by brentvollebregt** [comment]
What version of PyInstaller is being used (I believe it is shown in the output above this exception)

**Comment by NONPLAYT** [comment]
> What version of PyInstaller is being used? (I believe it is shown in the output above this exception)

4.7

**Comment by NONPLAYT** [comment]
Now I get this error
Python 3.10 is supported or how to fix this error?

```An error occurred while packaging
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pefile.py", line 2795, in __parse__
    fd = open(fname, "rb")
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\tmp2uxf6_cz\\build\\main\\main.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 782, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 714, in build
    exec(code, spec_namespace)
  File "C:\Users\Admin\AppData\Local\Temp\tmp2uxf6_cz\main.spec", line 23, in <module>
    exe = EXE(pyz,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\api.py", line 507, in __init__
    self.__postinit__()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\datastruct.py", line 155, in __postinit__
    self.assemble()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\api.py", line 726, in assemble
    set_exe_checksum(self.name)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\utils\win32\winutils.py", line 161, in set_exe_checksum
    pe = pefile.PE(exe_path)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pefile.py", line 2743, in __init__
    self.__parse__(name, data, fast_load)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pefile.py", line 2807, in __parse__
    raise Exception(
Exception: Unable to access file 'C:\Users\Admin\AppData\Local\Temp\tmp2uxf6_cz\build\main\main.exe': [Errno 22] Invalid argument: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\tmp2uxf6_cz\\build\\main\\main.exe'

Project output will not be moved to output folder
Complete.
