### ISSUE TITLE
Path and/or BootLoader reference error(s) on Raspberry Pi?

### ISSUE THREAD

**Issue by RoarkDority** [brentvollebregt/auto-py-to-exe#236]
Hi Brent,

I am trying with different examples on a Raspberry Pi and get these errors.  (below)

Questions:

I think I need to fix the path error(s) shown (/home/pi/.local/lib/python3.7/...
How to remove the prepended /home/pi from the rest of the path?

Also, is there something I need to do to avoid the BOOTLOADER reference error (near the end)?

Thanks in advance!  :-)

Greets,
Roark
Pixel Studio West

An error occurred while packaging
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/auto_py_to_exe/packaging.py", line 131, in package
    run_pyinstaller()
  File "/home/pi/.local/lib/python3.7/site-packages/PyInstaller/__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/pi/.local/lib/python3.7/site-packages/PyInstaller/__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 793, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/pi/.local/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 725, in build
    exec(code, spec_namespace)
  File "/tmp/tmpqgi4i41l/combinder.spec", line 40, in <module>
    entitlements_file=None )
  File "/home/pi/.local/lib/python3.7/site-packages/PyInstaller/building/api.py", line 508, in __init__
    self.__postinit__()
  File "/home/pi/.local/lib/python3.7/site-packages/PyInstaller/building/datastruct.py", line 155, in __postinit__
    self.assemble()
  File "/home/pi/.local/lib/python3.7/site-packages/PyInstaller/building/api.py", line 593, in assemble
    raise SystemExit(_MISSING_BOOTLOADER_ERRORMSG)
SystemExit: Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. For more details and instructions how to build the bootloader see
<https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html>

**Comment by brentvollebregt** [comment]
Did you read the link in the error? 

A search in Google for "pyinstaller bootloader raspberry pi" lead me to https://stackoverflow.com/a/55550762 which offers help on the missing bootloader.
