### ISSUE TITLE
pygame zero exe not working

### ISSUE THREAD

**Issue by ghost** [brentvollebregt/auto-py-to-exe#243]
Hi

I'm an autistic girl trying to make exe from a pygame zero code.
Is it possible to read here my problem?
I only have this problem with pygame zero games, not with pygame games.
I don't know what to do because I also don't understand this weird error about an icon I don't even use in my code! :-(

https://github.com/lordmauve/pgzero/issues/283

Thx

**Comment by brentvollebregt** [comment]
Is much more helpful when the error is here:

```
Traceback (most recent call last):
File "tigerheli.py", line 2, in
File "", line 1027, in _find_and_load
File "", line 1006, in _find_and_load_unlocked
File "", line 688, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "pgzrun.py", line 23, in
File "pgzero\runner.py", line 106, in prepare_mod
File "pgzero\game.py", line 92, in show_default_icon
File "pkgutil.py", line 639, in get_data
File "PyInstaller\loader\pyimod03_importers.py", line 344, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\GEBRUI~1\AppData\Local\Temp\_MEI183602\pgzero\data\icon.png'
```

**Comment by brentvollebregt** [comment]
It looks like the application you are bundling is looking for icon.png however it has not been included in the additional data.
Most likely [this file](https://github.com/lordmauve/pgzero/blob/master/pgzero/data/icon.png).

**Comment by pygamedev** [comment]
How to solve this in auto-py-to-exe?

Because a pygame game is converted perfectly, but not a pygame zero game.

**Comment by brentvollebregt** [comment]
Check out "[FileNotFoundError: [Errno 2] No such file or directory](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#filenotfounderror-errno-2-no-such-file-or-directory)" in the help post I have written - you will need to add the file manually using the "Additional Files" section in the UI. This is not an issue with auto-py-to-exe.

**Comment by pygamedev** [comment]
Hi

I selected "Additional Files" and then "Add Files" and I have chosen the icon.png

Now the error is changed to this So it has another folder but still can't find the file. The folder in the error is now the folder where the EXE was written.

pygame 2.1.2 (SDL 2.0.18, Python 3.10.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "tigerheli.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pgzrun.py", line 23, in <module>
  File "pgzero\runner.py", line 106, in prepare_mod
  File "pgzero\game.py", line 92, in show_default_icon
  File "pkgutil.py", line 639, in get_data
  File "PyInstaller\loader\pyimod03_importers.py", line 344, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Visual Studio project\\PYTHON\\DreamSoft Games\\output\\tigerheli\\pgzero\\data\\icon.png'
[16572] Failed to execute script 'tigerheli' due to unhandled exception!

**Comment by brentvollebregt** [comment]
Have you put the file in the right place? In the [help post I supply](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/), I states:

> For files that have been included but this error is still showing, package to one-directory instead of one-file to make sure things are working.

Have you used one-directory mode to check if the file is in the right place?

**Comment by pygamedev** [comment]
Is it possible to tell me step by step what to do?

- I have the file, in what folder do I copy it? Do I have to copy it to a subfolder \pgzero\data ?

- What option(s) I have to choise in auto-py-to-exe?


I can't find it, I keep getting error

**Comment by brentvollebregt** [comment]
When adding a file or folder in auto-py-to-exe, there are two boxes to fill out: the source location and the destination.

- The source location is where the file currently is on your disk. Using "Add Files" or "Add Folder" will auto-populate this field for you.
- The destination is where the file/folder will be put inside the final executable/folder. For example, if you have a file called icon.png and your code expects it to be in the folder "assets/images/" relative to your script, then you should put in "assets/images/".
