### ISSUE TITLE
SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by wanghaisheng** [brentvollebregt/auto-py-to-exe#269]
```
1291336 WARNING: Hidden import "pkg_resources.py2_warn" not found!
1291342 WARNING: Hidden import "pkg_resources.markers" not found!
1291373 INFO: Loading module hook 'hook-pygments.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1294037 INFO: Loading module hook 'hook-PyQt5.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1294677 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1294880 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1295254 INFO: Loading module hook 'hook-PyQt5.QtSvg.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1295964 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1296514 INFO: Loading module hook 'hook-pytz.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1296791 INFO: Loading module hook 'hook-scipy.io.matlab.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1296798 INFO: Loading module hook 'hook-scipy.linalg.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1296804 INFO: Loading module hook 'hook-scipy.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1296828 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1296842 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1297282 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1297289 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1297302 INFO: Loading module hook 'hook-scipy.stats._stats.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1297318 INFO: Loading module hook 'hook-setuptools.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1305021 INFO: Loading module hook 'hook-shelve.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1305035 INFO: Loading module hook 'hook-sphinx.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
1322964 INFO: Loading module hook 'hook-sqlalchemy.py' from 'D:\\Program Files\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
An error occurred while packaging
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\site-packages\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "D:\Program Files\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\Program Files\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\Program Files\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 845, in main
    build(specfile, distpath, workpath, clean_build)
  File "D:\Program Files\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 767, in build
    exec(code, spec_namespace)
  File "C:\Users\dubo\AppData\Local\Temp\tmpzu68hpn1\autovideo.spec", line 7, in <module>
    a = Analysis(
  File "D:\Program Files\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 319, in __init__
    self.__postinit__()
  File "D:\Program Files\anaconda3\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "D:\Program Files\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 487, in assemble
    self.graph.process_post_graph_hooks(self)
  File "D:\Program Files\anaconda3\lib\site-packages\PyInstaller\depend\analysis.py", line 326, in process_post_graph_hooks
    module_hook.post_graph(analysis)
  File "D:\Program Files\anaconda3\lib\site-packages\PyInstaller\depend\imphook.py", line 398, in post_graph
    self._load_hook_module()
  File "D:\Program Files\anaconda3\lib\site-packages\PyInstaller\depend\imphook.py", line 361, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
  File "D:\Program Files\anaconda3\lib\site-packages\PyInstaller\compat.py", line 620, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Program Files\anaconda3\lib\site-packages\PyInstaller\hooks\hook-sqlalchemy.py", line 31, in <module>
    dialects = eval(dialects.strip())
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Project output will not be moved to output folder
```

python 3.9

windows

sourcecode
https://github.com/wanghaisheng/autovideopublish/blob/main/autovideo.py

**Comment by brentvollebregt** [comment]
Could you provide the whole output from the tool?

**Comment by wanghaisheng** [comment]
@brentvollebregt  thanks very much

i just uninstall sqlalchemy....
