### ISSUE TITLE
auto-py-to-exe ImportError

### ISSUE THREAD

**Issue by Envases** [brentvollebregt/auto-py-to-exe#273]
Hi Guys

I have recently tried to install auto-py-to-exe and had no errors at this step. The problem comes when I try to run the code. I get an error as follows:

ImportError: cannot import name 'chrome' from 'eel'

Complete Trace Log

C:>auto-py-to-exe
Traceback (most recent call last):
File "C:\Users\ANaberan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
return run_code(code, main_globals, None,
File "C:\Users\ANaberan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "C:\Users\ANaberan\AppData\Local\Programs\Python\Python310\Scripts\auto-py-to-exe.exe_main.py", line 4, in
File "C:\Users\ANaberan\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_py_to_exe_main.py", line 10, in
from . import ui
File "C:\Users\ANaberan\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_py_to_exe\ui.py", line 8, in
from . import utils
File "C:\Users\ANaberan\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_py_to_exe\utils.py", line 8, in
from eel import chrome
ImportError: cannot import name 'chrome' from 'eel' (unknown location)

C:>

Just to let you know.

**Comment by Envases** [comment]
Forhot to add, I have installed auto-py-to-exe 2.19.0 with Python 3.10

**Comment by Envases** [comment]
and Pyinstaller 5.1 installed

**Comment by brentvollebregt** [comment]
What version of Eel do you have installed?

**Comment by Envases** [comment]
I had ![Eel upgrade Log](https://user-images.githubusercontent.com/42238206/169282253-1bfe34b6-21aa-48f8-98c1-014753d1b856.png) 0.12.4 installed. I tried to update it as you mentioned it to 0.14.0, but in doing so, it notifies me that it is incompatible with  auto-py-to-exe 2.19.0. I have attached an image capture of the log.

**Comment by Envases** [comment]
Must I uninstall Eel 0.14.0?

**Comment by Envases** [comment]
In spite of this, now it works or at least the application  turns up.

**Comment by brentvollebregt** [comment]
This project requires Eel 0.14.0 - this is enforced in requirements.txt and the setup script.

Looking at your screenshot, before you ran `pip install -U Eel`, you had 0.12.4 installed. The screenshot also shows you have now installed 0.14.0 - thus why it is working now.
