### ISSUE TITLE
The packaging is successful, but there is a problem with the operation, please answer

### ISSUE THREAD

**Issue by tea513** [brentvollebregt/auto-py-to-exe#278]
first 
```
1. My dependent files are all packaged using relative paths, so there should be no path problems
2. It can run perfectly and normally on pycharm, the compilation is successful, but there will be errors when running
```

compile command line
```
`pyinstaller --noconfirm --onefile --console  "D:/513/py_wombo/main.py"`
```

compile output
```
Running auto-py-to-exe v2.20.1
Building directory: C:\Users\ADMINI~1\AppData\Local\Temp\tmplk0oclmi
Provided command: pyinstaller --noconfirm --onefile --console  "D:/513/py_wombo/main.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --console D:/513/py_wombo/main.py --distpath C:\Users\ADMINI~1\AppData\Local\Temp\tmplk0oclmi\application --workpath C:\Users\ADMINI~1\AppData\Local\Temp\tmplk0oclmi\build --specpath C:\Users\ADMINI~1\AppData\Local\Temp\tmplk0oclmi
26934 INFO: PyInstaller: 5.1
26949 INFO: Python: 3.9.10
26967 INFO: Platform: Windows-10-10.0.19041-SP0
26982 INFO: wrote C:\Users\ADMINI~1\AppData\Local\Temp\tmplk0oclmi\main.spec
27000 INFO: UPX is not available.
27017 INFO: Extending PYTHONPATH with paths
['D:\\513\\py_wombo']
27389 INFO: checking Analysis
27397 INFO: Building Analysis because Analysis-00.toc is non existent
27400 INFO: Initializing module dependency graph...
27417 INFO: Caching module graph hooks...
27434 INFO: Analyzing base_library.zip ...
29178 INFO: Processing pre-find module path hook distutils from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
29187 INFO: distutils: retargeting to non-venv dir 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib'
31260 INFO: Caching module dependency graph...
31379 INFO: running Analysis Analysis-00.toc
31433 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe
31582 INFO: Analyzing D:\513\py_wombo\main.py
31697 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
33615 INFO: Processing module hooks...
33616 INFO: Loading module hook 'hook-certifi.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
33653 INFO: Loading module hook 'hook-cryptography.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
34221 INFO: Loading module hook 'hook-selenium.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
34407 INFO: Loading module hook 'hook-difflib.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34419 INFO: Loading module hook 'hook-distutils.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34419 INFO: Loading module hook 'hook-distutils.util.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34434 INFO: Loading module hook 'hook-encodings.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34516 INFO: Loading module hook 'hook-heapq.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34524 INFO: Loading module hook 'hook-lib2to3.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34567 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34570 INFO: Loading module hook 'hook-pickle.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34584 INFO: Loading module hook 'hook-platform.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34601 INFO: Loading module hook 'hook-sysconfig.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34618 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34633 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34652 INFO: Loading module hook 'hook-xml.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34653 INFO: Loading module hook 'hook-_tkinter.py' from 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
34873 INFO: checking Tree
34887 INFO: Building Tree because Tree-00.toc is non existent
34902 INFO: Building Tree Tree-00.toc
34964 INFO: checking Tree
34968 INFO: Building Tree because Tree-01.toc is non existent
34983 INFO: Building Tree Tree-01.toc
35081 INFO: checking Tree
35095 INFO: Building Tree because Tree-02.toc is non existent
35103 INFO: Building Tree Tree-02.toc
35166 INFO: Looking for ctypes DLLs
35182 INFO: Analyzing run-time hooks ...
35186 INFO: Including run-time hook 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
35186 INFO: Including run-time hook 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
35204 INFO: Including run-time hook 'D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
35221 INFO: Looking for dynamic libraries
36064 INFO: Looking for eggs
36076 INFO: Using Python library C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python39.dll
36084 INFO: Found binding redirects: 
[]
36084 INFO: Warnings written to C:\Users\ADMINI~1\AppData\Local\Temp\tmplk0oclmi\build\main\warn-main.txt
36166 INFO: Graph cross-reference written to C:\Users\ADMINI~1\AppData\Local\Temp\tmplk0oclmi\build\main\xref-main.html
36193 INFO: checking PYZ
36194 INFO: Building PYZ because PYZ-00.toc is non existent
36196 INFO: Building PYZ (ZlibArchive) C:\Users\ADMINI~1\AppData\Local\Temp\tmplk0oclmi\build\main\PYZ-00.pyz
36577 INFO: Building PYZ (ZlibArchive) C:\Users\ADMINI~1\AppData\Local\Temp\tmplk0oclmi\build\main\PYZ-00.pyz completed successfully.
36587 INFO: checking PKG
36601 INFO: Building PKG because PKG-00.toc is non existent
36617 INFO: Building PKG (CArchive) main.pkg
38802 INFO: Building PKG (CArchive) main.pkg completed successfully.
38813 INFO: Bootloader D:\513\py_wombo\venv\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
38819 INFO: checking EXE
38835 INFO: Building EXE because EXE-00.toc is non existent
38850 INFO: Building EXE from EXE-00.toc
38867 INFO: Copying bootloader EXE to C:\Users\ADMINI~1\AppData\Local\Temp\tmplk0oclmi\application\main.exe.notanexecutable
38868 INFO: Copying icon to EXE
38884 INFO: Copying icons from ['D:\\513\\py_wombo\\venv\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
38885 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
38901 INFO: Writing RT_ICON 1 resource with 3752 bytes
38917 INFO: Writing RT_ICON 2 resource with 2216 bytes
38919 INFO: Writing RT_ICON 3 resource with 1384 bytes
38934 INFO: Writing RT_ICON 4 resource with 37019 bytes
38935 INFO: Writing RT_ICON 5 resource with 9640 bytes
38951 INFO: Writing RT_ICON 6 resource with 4264 bytes
38967 INFO: Writing RT_ICON 7 resource with 1128 bytes
38986 INFO: Copying 0 resources to EXE
39002 INFO: Embedding manifest in EXE
39018 INFO: Updating manifest in C:\Users\ADMINI~1\AppData\Local\Temp\tmplk0oclmi\application\main.exe.notanexecutable
39019 INFO: Updating resource type 24 name 1 language 0
39019 INFO: Appending PKG archive to EXE
41036 INFO: Building EXE from EXE-00.toc completed successfully.

Moving project to: C:\Users\Administrator\Desktop\auto_video
Complete.

program execution error message
main.py:392: DeprecationWarning: use options instead of chrome_options

DevTools listening on ws://127.0.0.1:54215/devtools/browser/cbe62b0c-963a-4940-bb27-a812f27b2d15
错误: 没有找到进程 "ffmpeg.exe"。
错误: 没有找到进程 "ffprobe.exe"。
音乐下载地址=http://dhvexktaalgrs.cloudfront.net/3737.mp3
[9420:2056:0526/233822.734:ERROR:device_event_log_impl.cc(214)] [23:38:22.741] Bluetooth: bluetooth_adapter_winrt.cc:1075 Getting Default Adapter failed.
ffprobe version N-106490-gbb4e0f6162-20220402 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220402
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 25.100 / 59. 25.100
  libavformat    59. 20.101 / 59. 20.101
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 30.100 /  8. 30.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
[mp3 @ 000001d545482600] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'music_temp.mp3':
  Metadata:
    encoded_by      : Lavf52.1.0
  Duration: 00:01:44.23, start: 0.000000, bitrate: 64 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 64 kb/s
音乐秒数=104
ffmpeg version N-106490-gbb4e0f6162-20220402 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220402
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 25.100 / 59. 25.100
  libavformat    59. 20.101 / 59. 20.101
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 30.100 /  8. 30.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
[mp3 @ 00000278a0ab2780] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'music_temp.mp3':
  Metadata:
    encoded_by      : Lavf52.1.0
  Duration: 00:01:44.23, start: 0.000000, bitrate: 64 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 64 kb/s
Output #0, mp3, to 'output.mp3':
  Metadata:
    TENC            : Lavf52.1.0
    TSSE            : Lavf59.20.101
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 64 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=     125kB time=00:00:16.01 bitrate=  64.1kbits/s speed=1.07e+04x
video:0kB audio:125kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.214669%
错误: 没有找到进程 "ffmpeg.exe"。
错误: 没有找到进程 "ffprobe.exe"。
音乐下载地址=http://dhvexktaalgrs.cloudfront.net/3183.mp3
ffprobe version N-106490-gbb4e0f6162-20220402 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220402
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 25.100 / 59. 25.100
  libavformat    59. 20.101 / 59. 20.101
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 30.100 /  8. 30.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
[mp3 @ 0000018ae7962600] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'music_temp.mp3':
  Metadata:
    encoded_by      : Lavf52.1.0
  Duration: 00:01:09.90, start: 0.000000, bitrate: 64 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 64 kb/s
音乐秒数=69
ffmpeg version N-106490-gbb4e0f6162-20220402 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220402
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 25.100 / 59. 25.100
  libavformat    59. 20.101 / 59. 20.101
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 30.100 /  8. 30.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
[mp3 @ 000001a54df02780] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'music_temp.mp3':
  Metadata:
    encoded_by      : Lavf52.1.0
  Duration: 00:01:09.90, start: 0.000000, bitrate: 64 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 64 kb/s
Output #0, mp3, to 'output.mp3':
  Metadata:
    TENC            : Lavf52.1.0
    TSSE            : Lavf59.20.101
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 64 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=     125kB time=00:00:16.01 bitrate=  64.1kbits/s speed=1.06e+04x
video:0kB audio:125kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.214669%
Traceback (most recent call last):
  File "main.py", line 400, in <module>
  File "main.py", line 229, in 主程序
  File "essential_generators\document_generator.py", line 37, in __init__
  File "essential_generators\markov_wordgen.py", line 18, in __init__
  File "essential_generators\markov_wordgen.py", line 134, in load_model
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI25002\\essential_generators/markov_wordgen.json'
```

During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "main.py", line 406, in <module>
  File "main.py", line 229, in 主程序
  File "essential_generators\document_generator.py", line 37, in __init__
  File "essential_generators\markov_wordgen.py", line 18, in __init__
  File "essential_generators\markov_wordgen.py", line 134, in load_model
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI25002\\essential_generators/markov_wordgen.json'
[12416] Failed to execute script 'main' due to unhandled exception!
[9420:2056:0526/233828.979:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: The message port closed before a response was received.", source: https://ogs.google.com/u/0/widget/app?origin=chrome-untrusted%3A%2F%2Fnew-tab-page&origin=chrome%3A%2F%2Fnew-tab-page&cn=app&pid=1&spid=243&hl=zh-CN (0)
[9420:2056:0526/233829.598:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: The message port closed before a response was received.", source: https://ogs.google.com/u/0/widget/app?origin=chrome-untrusted%3A%2F%2Fnew-tab-page&origin=chrome%3A%2F%2Fnew-tab-page&cn=app&pid=1&spid=243&hl=zh-CN (0)
```

**Comment by brentvollebregt** [comment]
This is looking a bit messy and I'm not quite sure what's going on. Could you possibly use the bug report template?

From what I can gather, you executed `pyinstaller --noconfirm --onefile --console "D:/513/py_wombo/main.py"` and got errors? This repo is for auto-py-to-exe - if it is a pyinstaller issue, I recommend raising the bug in the pyinstaller repo with clear reproduction steps.

**Comment by brentvollebregt** [comment]
@tea513 you've put "please answer" in the title but did not reply to the help I've offered you - I feel like this is a bit rude.
