### ISSUE TITLE
struct.error: unpack requires a buffer of 16 bytes

### ISSUE THREAD

**Issue by Backist** [brentvollebregt/auto-py-to-exe#279]
I try to compile a python file into a ``.exe`` file, but when i execute the process, an error raises: ``unpack requires a buffer of 16 bytes``:
how can i solve this problem?
```
Running auto-py-to-exe v2.19.0
Building directory: C:\Users\Usuario\AppData\Local\Temp\tmpy37hk3r4
Provided command: pyinstaller --noconfirm --onefile --console --icon "C:/Users/Usuario/Desktop/Programacion/depositphotos_2076034-stock-photo-question-mark-and-thinker.ico"  "C:/Users/Usuario/Desktop/Programacion/como_sera_tu_vida.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --console --icon C:/Users/Usuario/Desktop/Programacion/depositphotos_2076034-stock-photo-question-mark-and-thinker.ico C:/Users/Usuario/Desktop/Programacion/como_sera_tu_vida.py --distpath C:\Users\Usuario\AppData\Local\Temp\tmpy37hk3r4\application --workpath C:\Users\Usuario\AppData\Local\Temp\tmpy37hk3r4\build --specpath C:\Users\Usuario\AppData\Local\Temp\tmpy37hk3r4

55099 INFO: PyInstaller: 5.0.1
55099 INFO: Python: 3.10.1
55111 INFO: Platform: Windows-10-10.0.19044-SP0
55129 INFO: wrote C:\Users\Usuario\AppData\Local\Temp\tmpy37hk3r4\como_sera_tu_vida.spec
55144 INFO: UPX is not available.
55160 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Usuario\\Desktop\\Programacion']
55607 INFO: checking Analysis
55608 INFO: Building Analysis because Analysis-01.toc is non existent
55609 INFO: Reusing cached module dependency graph...
55661 INFO: Caching module graph hooks...
55741 INFO: running Analysis Analysis-01.toc
55743 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\Usuario\AppData\Local\Programs\Python\Python310\python.exe
55792 INFO: Analyzing C:\Users\Usuario\Desktop\Programacion\como_sera_tu_vida.py
55797 INFO: Processing module hooks...
55798 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
55799 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
55811 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
55827 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
55911 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
55923 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
55975 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
55987 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
56003 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
56018 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
56033 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
56093 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
56242 INFO: checking Tree
56243 INFO: Building Tree because Tree-03.toc is non existent
56255 INFO: Building Tree Tree-03.toc
56346 INFO: checking Tree
56348 INFO: Building Tree because Tree-04.toc is non existent
56365 INFO: Building Tree Tree-04.toc
56469 INFO: checking Tree
56476 INFO: Building Tree because Tree-05.toc is non existent
56492 INFO: Building Tree Tree-05.toc
56522 INFO: Looking for ctypes DLLs
56547 INFO: Analyzing run-time hooks ...
56555 INFO: Including run-time hook 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
56571 INFO: Including run-time hook 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
56574 INFO: Including run-time hook 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
56587 INFO: Including run-time hook 'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
56605 INFO: Looking for dynamic libraries
57191 INFO: Looking for eggs
57206 INFO: Using Python library C:\Users\Usuario\AppData\Local\Programs\Python\Python310\python310.dll
57207 INFO: Found binding redirects: 
[]
57228 INFO: Warnings written to C:\Users\Usuario\AppData\Local\Temp\tmpy37hk3r4\build\como_sera_tu_vida\warn-como_sera_tu_vida.txt
57263 INFO: Graph cross-reference written to C:\Users\Usuario\AppData\Local\Temp\tmpy37hk3r4\build\como_sera_tu_vida\xref-como_sera_tu_vida.html
57289 INFO: checking PYZ
57301 INFO: Building PYZ because PYZ-01.toc is non existent
57316 INFO: Building PYZ (ZlibArchive) C:\Users\Usuario\AppData\Local\Temp\tmpy37hk3r4\build\como_sera_tu_vida\PYZ-01.pyz
57639 INFO: Building PYZ (ZlibArchive) C:\Users\Usuario\AppData\Local\Temp\tmpy37hk3r4\build\como_sera_tu_vida\PYZ-01.pyz completed successfully.
57673 INFO: checking PKG
57678 INFO: Building PKG because PKG-01.toc is non existent
57694 INFO: Building PKG (CArchive) como_sera_tu_vida.pkg
58875 INFO: Building PKG (CArchive) como_sera_tu_vida.pkg completed successfully.
58882 INFO: Bootloader C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
58898 INFO: checking EXE
58913 INFO: Building EXE because EXE-01.toc is non existent
58929 INFO: Building EXE from EXE-01.toc
58945 INFO: Copying bootloader EXE to C:\Users\Usuario\AppData\Local\Temp\tmpy37hk3r4\application\como_sera_tu_vida.exe.notanexecutable
59112 INFO: Copying icon to EXE
59121 INFO: Copying icons from ['C:\\Users\\Usuario\\Desktop\\Programacion\\depositphotos_2076034-stock-photo-question-mark-and-thinker.ico']
An error occurred while packaging
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 845, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 767, in build
    exec(code, spec_namespace)
  File "C:\Users\Usuario\AppData\Local\Temp\tmpy37hk3r4\como_sera_tu_vida.spec", line 24, in <module>
    exe = EXE(
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\api.py", line 524, in __init__
    self.__postinit__()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\api.py", line 629, in assemble
    icon.CopyIcons(build_name, self.icon)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\utils\win32\icon.py", line 215, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\utils\win32\icon.py", line 150, in CopyIcons_FromIco
    for i, f in enumerate(icons):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\utils\win32\icon.py", line 114, in __init__
    entry.fromfile(file)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\utils\win32\icon.py", line 71, in fromfile
    self._fields_ = list(struct.unpack(self._format_, data))
struct.error: unpack requires a buffer of 16 bytes

Project output will not be moved to output folder
Complete.
```

**Comment by brentvollebregt** [comment]
A couple of questions first:
1. Did you search for this issue in the existing GitHub issues first? #44 looks pretty similar.
2. Did you read the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe) which is linked in the README, the top of the application and at the bottom of the application at the end of *every* build?

Searching for your error "struct.error: unpack requires a buffer of 16 bytes" in the help post, there is [a whole section for this common mistake](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#structerror-unpack-requires-a-buffer-of-16-bytes).

You haven't said anything about providing an icon but I have a feeling you may have put a file in the icon field that is not a valid .ico file.
