### ISSUE TITLE
SyntaxError when specifying arg name

### ISSUE THREAD

**Issue by cohi99** [brentvollebregt/auto-py-to-exe#282]
I ran it manually with pyinstaller and with auto-py-to-exe.

Everytime I tried to specify name I got this error (I tried -n Name, -n "Name", --name "Name"):

10978 INFO: Copying version information to EXE
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 842, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 764, in build
    exec(code, spec_namespace)
  File "C:\Users\user\Desktop\.exe\.exe\src\struna_package\Struna.spec", line 28, in <module>
    exe = EXE(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\api.py", line 524, in __init__
    self.__postinit__()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\api.py", line 633, in assemble
    versioninfo.SetVersion(build_name, self.versrsrc)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 565, in SetVersion
    vs = eval(txt)
  File "<string>", line 2
    name = Struna
    ^^^^
SyntaxError: invalid syntax

**Comment by brentvollebregt** [comment]
If you tried the syntax `--name NAME` with PyInstaller itself and it failed, then this will be a PyInstaller issue that I cannot fix.

What version of Python are you using? What version of auto-py-to-exe are you using? What version of PyInstaller are you using? Could you please fill out the template - would have saved a couple of questions.
