### ISSUE TITLE
Error while installing auto-py-to-exe

### ISSUE THREAD

**Issue by VinaySavla** [brentvollebregt/auto-py-to-exe#295]
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\vinay\AppData\Local\Temp\pip-install-38_pf_2g\eel_6f37b3bdacc4416b97f5ce2f5d88e824\setup.py", line 7, in <module>
          setup(
        File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 453, in __init__
          _Distribution.__init__(
        File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 292, in __init__
          self.finalize_options()
        File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 830, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 829, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
          return self.resolve()
        File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
          module = __import__(self.module_name, fromlist=['__name__'], level=0)
        File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\py2app\build_app.py", line 37, in <module>
          from py2app.create_appbundle import create_appbundle
        File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\py2app\create_appbundle.py", line 9, in <module>
          from py2app.util import make_exec, makedirs, mergecopy, mergetree, skipscm
        File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\py2app\util.py", line 5, in <module>
          import fcntl
      ModuleNotFoundError: No module named 'fcntl'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by VinaySavla** [comment]
i am using windows 10
python 3.10.0

**Comment by brentvollebregt** [comment]
Can you please fill out the issue template. I don't see any reproduction steps here.

**Comment by VinaySavla** [comment]
When I tried to install auto-py-to-exe it showed me the error that Module not found named FCNTL

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

> If you have example code, please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Your Environment:**
- Python version (`python --version`):
- auto-py-to-exe version (`pip show auto-py-to-exe`):
- PyInstaller version (`pip show pyinstaller`):
- Eel version (`pip show eel`): 

**Additional context**
Add any other context about the problem here.

**Comment by VinaySavla** [comment]
When I tried installing auto-py-to-exe it showed me the error that is in my first comment. 


Steps to reproduce the behavior:
1. Open Command Prompt
2. Type "pip install auto-py-to-exe"


Expected behavior
It should have been installed

**Screenshots**
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [28 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "C:\Users\vinay\AppData\Local\Temp\pip-install-38_pf_2g\eel_6f37b3bdacc4416b97f5ce2f5d88e824\setup.py", line 7, in
setup(
File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools_init_.py", line 153, in setup
return distutils.core.setup(**attrs)
File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 108, in setup
setup_distribution = dist = klass(attrs)
File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 453, in init
Distribution.init(
File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 292, in init
self.finalize_options()
File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 830, in finalize_options
for ep in sorted(loaded, key=by_order):
File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 829, in
loaded = map(lambda e: e.load(), filtered)
File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources_init.py", line 2450, in load
return self.resolve()
File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources_init.py", line 2456, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\py2app\build_app.py", line 37, in
from py2app.create_appbundle import create_appbundle
File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\py2app\create_appbundle.py", line 9, in
from py2app.util import make_exec, makedirs, mergecopy, mergetree, skipscm
File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\py2app\util.py", line 5, in
import fcntl
ModuleNotFoundError: No module named 'fcntl'
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Your Environment:**
- Python version 3.10.0
- auto-py-to-exe version 2.21.1 (was trying to install)

**Comment by brentvollebregt** [comment]
I just executed `pip install auto-py-to-exe` in a terminal and it was fine:

```
$ pip install --force-reinstall auto-py-to-exe
Collecting auto-py-to-exe
  Using cached auto_py_to_exe-2.21.1-py2.py3-none-any.whl (94 kB)

[removed for brevity (collecting packages and installing)...]

Successfully installed Eel-0.14.0 altgraph-0.17.2 auto-py-to-exe-2.21.1 bottle-0.12.23 bottle-websocket-0.2.9 cffi-1.15.1 future-0.18.2 gevent-21.12.0 gevent-websocket-0.10.1 greenlet-1.1.2 pefile-2022.5.30 pycparser-2.21 pyinstaller-5.3 pyinstaller-hooks-contrib-2022.8 pyparsing-3.0.9 pywin32-ctypes-0.2.0 setuptools-63.4.1 whichcraft-0.6.1 zope.event-4.5.0 zope.interface-5.4.0
```

Can you please run the command you are proposing to reproduce the issue in a virtual Python environment? If we can get a reproducible case, I will have to close this sorry. Giving more information about your environment setup would help.

**Comment by VinaySavla** [comment]
I am getting this issue in windows 10 machine as I mentioned in the start of the comment

**Comment by VinaySavla** [comment]
I am getting this issue in windows 10 machine as I mentioned in the start of the comment

**Comment by brentvollebregt** [comment]
I am also on Windows 10 - that is not the issue.

Can you please try to install the library in a virtual environment.

**Comment by VinaySavla** [comment]
Ok great, I'll try that. Thank you

**Comment by marsonbili-eng** [comment]
[end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
