### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by x17db19** [brentvollebregt/auto-py-to-exe#312]
output:
Running auto-py-to-exe v2.23.0
Building directory: C:\Users\block\AppData\Local\Temp\tmpzb62v235
Provided command: pyinstaller --noconfirm --onefile --console  "C:/Users/block/Desktop/U-Combat 2.0/EzSetup.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --console C:/Users/block/Desktop/U-Combat 2.0/EzSetup.py --distpath C:\Users\block\AppData\Local\Temp\tmpzb62v235\application --workpath C:\Users\block\AppData\Local\Temp\tmpzb62v235\build --specpath C:\Users\block\AppData\Local\Temp\tmpzb62v235

21808 INFO: PyInstaller: 4.6
21821 INFO: Python: 3.10.5
21862 INFO: Platform: Windows-10-10.0.19044-SP0
21868 INFO: wrote C:\Users\block\AppData\Local\Temp\tmpzb62v235\EzSetup.spec
21871 INFO: UPX is not available.
21884 INFO: Extending PYTHONPATH with paths
['C:\\Users\\block\\Desktop\\U-Combat 2.0']
22428 INFO: checking Analysis
22443 INFO: Building Analysis because Analysis-00.toc is non existent
22459 INFO: Initializing module dependency graph...
22464 INFO: Caching module graph hooks...
22494 WARNING: Several hooks defined for module 'numpy'. Please take care they do not conflict.
22501 INFO: Analyzing base_library.zip ...
27294 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\block\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
27302 INFO: distutils: retargeting to non-venv dir 'C:\\Users\\block\\AppData\\Local\\Programs\\Python\\Python310\\lib'
28401 INFO: Caching module dependency graph...
28554 INFO: running Analysis Analysis-00.toc
28578 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\block\AppData\Local\Programs\Python\Python310\python.exe
28646 INFO: Analyzing C:\Users\block\Desktop\U-Combat 2.0\EzSetup.py
28660 INFO: Processing module hooks...
28673 INFO: Loading module hook 'hook-clr.py' from 'C:\\Users\\block\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
An error occurred while packaging
Traceback (most recent call last):
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\depend\imphook.py", line 361, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\compat.py", line 594, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-clr.py", line 30, in <module>
    filepaths = [f for f in files('pythonnet') if 'Python.Runtime.dll' in str(f)]
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 1018, in files
    return distribution(distribution_name).files
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pythonnet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 782, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 714, in build
    exec(code, spec_namespace)
  File "C:\Users\block\AppData\Local\Temp\tmpzb62v235\EzSetup.spec", line 7, in <module>
    a = Analysis(['C:/Users/block/Desktop/U-Combat 2.0/EzSetup.py'],
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 277, in __init__
    self.__postinit__()
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\datastruct.py", line 155, in __postinit__
    self.assemble()
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 445, in assemble
    self.graph.process_post_graph_hooks(self)
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 326, in process_post_graph_hooks
    module_hook.post_graph(analysis)
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\depend\imphook.py", line 398, in post_graph
    self._load_hook_module()
  File "C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\depend\imphook.py", line 364, in _load_hook_module
    raise ImportErrorWhenRunningHook(self.hook_module_name, self.hook_filename)
PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_clr required by hook for module C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-clr.py. Please check whether module __PyInstaller_hooks_0_clr actually exists and whether the hook is compatible with your version of C:\Users\block\AppData\Local\Programs\Python\Python310\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-clr.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.

Project output will not be moved to output folder
Complete.

**Comment by brentvollebregt** [comment]
Can you please fill out the template you cleared out - dumping your error here with no context is not helpful whatsoever.
