### ISSUE TITLE
The browse button isn't working

### ISSUE THREAD

**Issue by fluentmoheshwar** [brentvollebregt/auto-py-to-exe#313]
**Quick Checks For You**
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+) looking for an issue similar to mine
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have made sure my applicaiton/script runs before trying to package

**Describe the bug**

**To Reproduce**
1. Run auto-py-to-exe
2. Click on browse
3. Nothing happens in GUI. This error logs in terminal
```text
Traceback (most recent call last):
  File "C:\Users\amarn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\eel\__init__.py", line 281, in _process_message
    return_val = _exposed_functions[message['name']](*message['args'])
  File "C:\Users\amarn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\auto_py_to_exe\ui.py", line 63, in ask_file
    return dialogs.ask_file(file_type)
  File "C:\Users\amarn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\auto_py_to_exe\dialogs.py", line 26, in ask_file
    root = Tk()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    {C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\tcl\tcl8.6}



This probably means that Tcl wasn't installed properly.
```
I tried running 
```bash
pip install Tcl
```
didn't worked

**Expected behavior**
It should open the browse popup

**Your Environment:**
- Python version (`python --version`): Python 3.10.6
- auto-py-to-exe version (`pip show auto-py-to-exe`): 2.23.0
- PyInstaller version (`pip show pyinstaller`): 5.3
- Eel version (`pip show eel`): 0.14.0

**Comment by fluentmoheshwar** [comment]
Fixed after a new python update!
