### ISSUE TITLE
Getting frozen runpy and dll error 

### ISSUE THREAD

**Issue by RajeshMahadevappa** [brentvollebregt/auto-py-to-exe#338]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Scripts\auto-py-to-exe.exe\__main__.py", line 4, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_py_to_exe\__main__.py", line 10, in <m
odule>
    from . import ui
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_py_to_exe\ui.py", line 5, in <module>
    import eel
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\eel\__init__.py", line 5, in <module>
    from gevent.threading import Timer
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\gevent\__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\gevent\_hub_local.py", line 101, in <module
>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\gevent\_util.py", line 148, in import_c_acc
el
    mod = importlib.import_module(cname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\\gevent\\_hub_local.py", line 1, in init gevent._gevent_c_hub_local
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _greenlet: The specified module could not be found.

**Comment by RajeshMahadevappa** [comment]
can some one help me to solve this, getting same error everywhere tried with more than 3 system

**Comment by brentvollebregt** [comment]
Looks like a duplicate of #325?
