### ISSUE TITLE
ValueError: Entry points must be listed in groups

### ISSUE THREAD

**Issue by Itsbgold001** [brentvollebregt/auto-py-to-exe#405]
Hi, I faced this error, please can you tell me how to  fix this
```

Traceback (most recent call last):
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 99, in discover_hook_directories
    entry_points = sorted(entry_points, key=lambda x: x.module_name == "_pyinstaller_hooks_contrib.hooks")
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 655, in <genexpr>
    for entry in dist.get_entry_map(group).values()
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 2868, in get_entry_map
    ep_map = self._ep_map = EntryPoint.parse_map(
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 2549, in parse_map
    raise ValueError("Entry points must be listed in groups")
ValueError: Entry points must be listed in groups
```

**Comment by brentvollebregt** [comment]
It looks like your setuptools might be out of date - run `pip install setuptools --upgrade` to update setuptools

**Comment by Itsbgold001** [comment]
Hi @brentvollebregt , it still gave me the error.
Here is the full log
```

Running auto-py-to-exe v2.36.0
Building directory: C:\Users\DAV\AppData\Local\Temp\tmpwxfo4qc5
Provided command: pyinstaller --noconfirm --onedir --console  "C:/Users/DAV/PycharmProjects/Baqee/main.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onedir --console C:/Users/DAV/PycharmProjects/Baqee/main.py --distpath C:\Users\DAV\AppData\Local\Temp\tmpwxfo4qc5\application --workpath C:\Users\DAV\AppData\Local\Temp\tmpwxfo4qc5\build --specpath C:\Users\DAV\AppData\Local\Temp\tmpwxfo4qc5

87698 INFO: PyInstaller: 5.13.0
87788 INFO: Python: 3.9.0
87831 INFO: Platform: Windows-10-10.0.19041-SP0
87949 INFO: wrote C:\Users\DAV\AppData\Local\Temp\tmpwxfo4qc5\main.spec
88129 INFO: Extending PYTHONPATH with paths
['C:\\Users\\DAV\\PycharmProjects\\Baqee']
An error occurred while packaging
Traceback (most recent call last):
  File "C:\Users\DAV\auto-py-to-exe\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 1019, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 944, in build
    exec(code, spec_namespace)
  File "C:\Users\DAV\AppData\Local\Temp\tmpwxfo4qc5\main.spec", line 7, in <module>
    a = Analysis(
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 373, in __init__
    self.hookspath += discover_hook_directories()
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\isolated\_parent.py", line 403, in wrapped
    return call(function, *args, **kwargs)
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\isolated\_parent.py", line 302, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to discover_hook_directories() failed with:
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 2936, in get_entry_map
    ep_map = self._ep_map
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 2902, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 99, in discover_hook_directories
    entry_points = sorted(entry_points, key=lambda x: x.module_name == "_pyinstaller_hooks_contrib.hooks")
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 712, in <genexpr>
    for entry in dist.get_entry_map(group).values()
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 2938, in get_entry_map
    ep_map = self._ep_map = EntryPoint.parse_map(
  File "C:\Users\DAV\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 2606, in parse_map
    raise ValueError("Entry points must be listed in groups")
ValueError: Entry points must be listed in groups

Project output will not be moved to output folder
Complete.

```

**Comment by brentvollebregt** [comment]
If you create a virtual environment and then install auto-py-to-exe, does this still happen?

Also, you have literally just pasted your error here with no context - this doesn't really give me anything to help you with. Could you maybe fill out the bug template to help me out a bit?
