### ISSUE TITLE
The 'pandas_profiling' package was not installed in a way that PackageLoader understands.

### ISSUE THREAD

**Issue by Mina4ever** [brentvollebregt/auto-py-to-exe#430]
**Quick Checks**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [x] I have made sure my application/script runs before trying to package 

**Describe the bug**
When trying to launch the output "exe" I faced the below issue 
ValueError: The 'pandas_profiling' package was not installed in a way that PackageLoader understands.

**To Reproduce**
Steps to reproduce the behavior (install dependencies, do this in the auto-py-to-exe UI):
1- I launched auto-py-to-exe GUI.
2- I extracted python script in py file (attached below) 
3- In auto-py-to-exe GUI , I have choose "file only" then process 
4- Whole process run successfully.
5- When trying to launch the output "exe" I faced the below issue
Traceback (most recent call last):
  File "DataQuilaty.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pandas_profiling\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pandas_profiling\compare_reports.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pandas_profiling\profile_report.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pandas_profiling\report\presentation\flavours\html\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pandas_profiling\report\presentation\flavours\html\alerts.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pandas_profiling\report\presentation\flavours\html\templates.py", line 11, in <module>
  File "jinja2\loaders.py", line 323, in __init__
ValueError: The 'pandas_profiling' package was not installed in a way that PackageLoader understands.

```python
# If you have example code, please provide a minimal reproducible example: 
import pandas as pd
from pandas_profiling import ProfileReport
import cx_Oracle
import tkinter as tk
prof = ProfileReport(df)
```

**Expected behavior**

**Your Environment:**
- Python version (`3.9.17`):
- auto-py-to-exe version (`2.38.0`):
- PyInstaller version (`5.13.2`):
- Eel version (`0.16.0`): 
[DataQuilaty.txt](https://github.com/brentvollebregt/auto-py-to-exe/files/12702806/DataQuilaty.txt)

**Comment by brentvollebregt** [comment]
It appears this may be an issue with the `pandas_profiling` itself - not auto-py-to-exe/PyInstaller. Doing a [quick search for "pyinstaller" in the repo for this library](https://github.com/ydataai/ydata-profiling/issues?q=is%3Aissue+pyinstaller), points me to ydataai/ydata-profiling#942 - this could be discussed more in ydataai/ydata-profiling#968.

**Comment by Mina4ever** [comment]
I went through all the above opened discussions and issues forms and I can't find any resolving for it , also I don't know where the below pieces of code should be inserted into ? :

# Initializing Jinja
if getattr(sys, 'frozen', False):
    # Support for PyInstaller
    bundle_dir = sys._MEIPASS
    package_loader = jinja2.FileSystemLoader(bundle_dir)
else:
    package_loader = jinja2.PackageLoader(
        "pandas_profiling", "report/presentation/flavours/html/templates"
    )

**Comment by brentvollebregt** [comment]
I have not used this library before so I'm unable to offer any assistance with it. I recommend asking in the discussion I linked as it's the same issue and in the repo of the library you are having the issue with.
