### ISSUE TITLE
Get some error and cant build .exe

### ISSUE THREAD

**Issue by mfirouzin** [brentvollebregt/auto-py-to-exe#44]
when I use .ico file i got this error but without icon file there is not any error!

50296 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
50310 INFO: Bootloader C:\Users\PowerMan\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
50310 INFO: checking EXE
50311 INFO: Building EXE because EXE-00.toc is non existent
50311 INFO: Building EXE from EXE-00.toc
50313 INFO: SRCPATH [('C:\\LCL\\icon.ico', None)]
50314 INFO: Updating icons from ['C:\\LCL\\icon.ico'] to C:\Users\PowerMan\AppData\Local\Temp\tmp2lbyh0dp
An error occurred, traceback follows:
Traceback (most recent call last):
  File "C:\Users\PowerMan\Desktop\auto-py-to-exe-master\auto_py_to_exe\__main__.py", line 217, in convert
    pyi.run() # Execute PyInstaller
  File "C:\Users\PowerMan\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\PowerMan\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\PowerMan\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\PowerMan\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 32, in <module>
  File "C:\Users\PowerMan\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\building\api.py", line 433, in __init__
    self.__postinit__()
  File "C:\Users\PowerMan\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "C:\Users\PowerMan\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\building\api.py", line 522, in assemble
    icon.CopyIcons(tmpnm, self.icon)
  File "C:\Users\PowerMan\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\utils\win32\icon.py", line 177, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
  File "C:\Users\PowerMan\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\utils\win32\icon.py", line 134, in CopyIcons_FromIco
    for i, f in enumerate(icons):
  File "C:\Users\PowerMan\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\utils\win32\icon.py", line 104, in __init__
    entry.fromfile(file)
  File "C:\Users\PowerMan\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\utils\win32\icon.py", line 65, in fromfile
    self._fields_ = list(struct.unpack(self._format_, data))
struct.error: unpack requires a buffer of 16 bytes

Project output will not be moved to output folder
Complete.

**Comment by brentvollebregt** [comment]
Was the .ico file you provided a valid icon file? You can't just rename the file to be .ico and use it.

Have you tried with a different icon file?

**Comment by mfirouzin** [comment]
> Was the .ico file you provided a valid icon file? You can't just rename the file to be .ico and use it.
> 
> Have you tried with a different icon file?

yes i change the icon name from icon.ico to another name and that sounds good!
