### ISSUE TITLE
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\threadpool.py", line 173, in __run_task     thread_result.set(func(*args, **kwargs)) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 3: invalid start byte

### ISSUE THREAD

**Issue by 2197808908a** [brentvollebregt/auto-py-to-exe#485]
PS D:\Desktop\diploma_project_Code\Gesture\Simple_Gesture_Interaction> auto-py-to-exe
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\threadpool.py", line 173, in __run_task
    thread_result.set(func(*args, **kwargs))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 3: invalid start byte
2024-05-21T03:19:15Z (<ThreadPoolWorker at 0x22076fb6d48 thread_ident=0x431c threadpool-hub=<Hub at 0x2207c5583b8 thread_ident=0x464>>, <built-in function gethostbyaddr>) failed with UnicodeDecodeError

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Scripts\auto-py-to-exe.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\auto_py_to_exe\__main__.py", line 106, in run
    start_ui(logging_level, args.build_directory_override)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\auto_py_to_exe\__main__.py", line 26, in start_ui
    ui.start(config.ui_open_mode)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\auto_py_to_exe\ui.py", line 182, in start
    eel.start("index.html", size=(650, 701), port=0)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\eel\__init__.py", line 200, in start
    run_lambda()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\eel\__init__.py", line 196, in run_lambda
    app=app) # Always returns None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\bottle.py", line 3175, in run
    server.run(app)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\bottle_websocket\server.py", line 17, in run
    server.serve_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\baseserver.py", line 398, in serve_forever
    self.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\baseserver.py", line 336, in start
    self.init_socket()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\pywsgi.py", line 1546, in init_socket
    self.update_environ()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\pywsgi.py", line 1558, in update_environ
    name = socket.getfqdn(address[0])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\_socketcommon.py", line 304, in getfqdn
    hostname, aliases, _ = gethostbyaddr(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\_socketcommon.py", line 276, in gethostbyaddr
    return get_hub().resolver.gethostbyaddr(ip_address)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\resolver\thread.py", line 66, in gethostbyaddr
    return self.pool.apply(_socket.gethostbyaddr, args, kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src\\gevent\\event.py", line 329, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 359, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 347, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 327, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\_compat.py", line 66, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\gevent\threadpool.py", line 173, in __run_task
    thread_result.set(func(*args, **kwargs))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 3: invalid start byte

**Comment by brentvollebregt** [comment]
Hi @2197808908a, can you please fill out the template your cleared. 

The content asked for in the temaplte gives context around how you got this - rather than just pasting an error and giving nothing else.
