### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by zinzied** [brentvollebregt/auto-py-to-exe#498]
Info: Installing shim for bottle import redirects (using Python=3.12.4 and bottle=0.12.25)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\HOPE\AppData\Local\Programs\Python\Python312\Scripts\auto-py-to-exe.exe\__main__.py", line 4, in <module>
  File "C:\Users\HOPE\AppData\Local\Programs\Python\Python312\Lib\site-packages\auto_py_to_exe\__main__.py", line 11, in <module>
    from . import __version__, config, ui, validation  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HOPE\AppData\Local\Programs\Python\Python312\Lib\site-packages\auto_py_to_exe\ui.py", line 6, in <module>
    import eel
  File "C:\Users\HOPE\AppData\Local\Programs\Python\Python312\Lib\site-packages\eel\__init__.py", line 12, in <module>
    from gevent.threading import Timer
  File "C:\Users\HOPE\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\__init__.py", line 
72, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\HOPE\AppData\Local\Programs\Python\Python312\Lib\site-packages\gevent\_hub_local.py", line 149, in <module>
    from gevent._util import import_c_accel
ModuleNotFoundError: No module named 'gevent._util'

**Comment by brentvollebregt** [comment]
When you installed the dependencies/requirements, did you see any errors? I recommend trying to install them again.
