### ISSUE TITLE
Failed to execute script

### ISSUE THREAD

**Issue by huseyincenik** [brentvollebregt/auto-py-to-exe#504]
**Quick Checks**

- [ +] I have read the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [ +] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine
- [ +] I have made sure my application/script runs before trying to package

**Describe the bug**

Hello, I get an error when I try to convert the streamlit application to exe. I tried hidden import but it did not work.
![image](https://github.com/user-attachments/assets/fadc43b7-1c48-4232-a2d7-c4fb020d0828)

**To Reproduce**

_Steps to reproduce the behavior (install dependencies, do this in the auto-py-to-exe UI):_

```python
# If you have example code, please provide a minimal reproducible example:
# https://stackoverflow.com/help/minimal-reproducible-example

print("Hello World")
```

**Expected behavior**

Traceback (most recent call last):
  File "langchain_fast.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "streamlit\__init__.py", line 64, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "streamlit\version.py", line 38, in <module>
  File "importlib\metadata\__init__.py", line 996, in version
  File "importlib\metadata\__init__.py", line 969, in distribution
  File "importlib\metadata\__init__.py", line 548, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for streamlit

**Your Environment:**

- Python version (`3.10.14`):
- auto-py-to-exe version (`2.44.2`):
- PyInstaller version (` 6.10.0`):
- Eel version (`0.17.0`):

**Comment by brentvollebregt** [comment]
Looks like this is an issue with packaging this specific library (streamlit) and not auto-py-to-exe or PyInstaller. I'll move this to a discussion as asked for in CONTRIBUTING.md.
