### ISSUE TITLE
"C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\importlib\metadata\__init__.py", line 179,

### ISSUE THREAD

**Issue by tnt6213274o6923** [brentvollebregt/auto-py-to-exe#506]
hi i'am suraphat i from thai pass help me brentvollebregt to the eror tha i un
translate by google translate

cmd:
PS H:\app system> auto-py-to-exe
Traceback (most recent call last):
  File "\\?\H:\app system\.venv\Scripts\auto-py-to-exe-script.py", line 33, in <module>
    sys.exit(load_entry_point('auto-py-to-exe==2.44.2', 'console_scripts', 'auto-py-to-exe')())
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\?\H:\app system\.venv\Scripts\auto-py-to-exe-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
           ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\importlib\metadata\__init__.py", line 179, in load
    module = import_module(match.group('module'))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "H:\app system\.venv\Lib\site-packages\auto_py_to_exe\__main__.py", line 11, in <module>
    from . import __version__, config, ui, validation  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\app system\.venv\Lib\site-packages\auto_py_to_exe\ui.py", line 9, in <module>
    from . import config, dialogs, packaging, utils
  File "H:\app system\.venv\Lib\site-packages\auto_py_to_exe\dialogs.py", line 26, in <module>
    root = Tk()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2459, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/Users/Admin/AppData/Local/Programs/Python/Python313/lib/tcl8.6 C:/Users/Admin/AppData/Local/Programs/Python/lib/tcl8.6 C:/Users/Admin/AppData/Local/Programs/lib/tcl8.6 C:/Users/Admin/AppData/Local/Programs/Python/library C:/Users/Admin/AppData/Local/Programs/library C:/Users/Admin/AppData/Local/Programs/tcl8.6.14/library C:/Users/Admin/AppData/Local/tcl8.6.14/library



This probably means that Tcl wasn't installe

-suraphat 
thank you

**Comment by tnt6213274o6923** [comment]
https://github.com/user-attachments/assets/b18cb286-f40d-44b4-a861-79bba374ffe4

**Comment by brentvollebregt** [comment]
Looks like this might be an issue in Python 3.13: https://github.com/python/cpython/issues/125235

Can you try a different Python version?

**Comment by tnt6213274o6923** [comment]
thank you for help
