### ISSUE TITLE
Sometimes auto-py-to-exe works, other times it poops:

### ISSUE THREAD

**Issue by enjoysmath** [brentvollebregt/auto-py-to-exe#81]
That out at the end of a long wait.

```
An error occurred, traceback follows:
Traceback (most recent call last):
  File "c:\python36_32\lib\site-packages\auto_py_to_exe\__main__.py", line 269, in convert
    pyi.run() # Execute PyInstaller
  File "c:\python36_32\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python36_32\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python36_32\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python36_32\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Users\FRUITF~1\AppData\Local\Temp\tmpasjau1wg\SoundUnitedCommandGUI.spec", line 17, in <module>
    noarchive=True)
  File "c:\python36_32\lib\site-packages\PyInstaller\building\build_main.py", line 243, in __init__
    self.__postinit__()
  File "c:\python36_32\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\python36_32\lib\site-packages\PyInstaller\building\build_main.py", line 597, in assemble
    for name, path, typecode in compile_py_files(new_toc, CONF['workpath']):
  File "c:\python36_32\lib\site-packages\PyInstaller\utils\misc.py", line 150, in compile_py_files
    with open(obj_fnm, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '-'

Project output will not be moved to output folder
```

I'll try restarting auto-py-to-exe and trying again.

**Comment by enjoysmath** [comment]
Unchecked debug: All and it works again.

**Comment by brentvollebregt** [comment]
Could you please export the configuration being used to package the script by using the export to JSON button in the advanced section. 
After the export, could you please paste the contents here.
