### ISSUE TITLE
I get errors when running python -m auto_py_to_exe

### ISSUE THREAD

**Issue by NikiTricky2** [brentvollebregt/auto-py-to-exe#95]
When i run `python -m auto_py_to_exe` i get:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Desktop\auto-py-to-exe-master\auto-py-to-exe-master\auto_py_to_exe\__main__.py", line 10, in <module>
    from . import ui
  File "C:\Users\User\Desktop\auto-py-to-exe-master\auto-py-to-exe-master\auto_py_to_exe\ui.py", line 5, in <module>
    import eel
ModuleNotFoundError: No module named 'eel'

I run on windows 7

**Comment by brentvollebregt** [comment]
I see you have downloaded/cloned the repository and I assume you are trying to run the application without installing. 

In the README state that you need to execute `python -m pip install -r requirements.txt` to install dependencies?  Have you done this? The error that you have provided hints you have not followed this instruction.

**Comment by NikiTricky2** [comment]
Thanks!
